### ISSUE TITLE
Text review for the hub section

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKnet-Website#10]
I think this is good for now, but as all texts will need a proper review we should create another branch for Review/Text corrections? @budarz might be of help

_Originally posted by @timmwille in https://github.com/ASKnet-Community/ASKnet.Community/pull/9#pullrequestreview-766010911_

**Comment by timmwille** [comment]
@yara89 can you help with this? I'll write Sara and Petra again but we might also ask @intertwilight for help as in Timeline

**Comment by yara89** [comment]
yep waiting for @intertwilight input!

**Comment by yara89** [comment]
I have already asked @intertwilight, and he has it on his priority list :) @timmwille so, soon enough I hope! ;) 🤞

**Comment by timmwille** [comment]
@intertwilight time is up :) we go for it without another review for now same as in #66  (content review done by Sara though, so it is ok for now)
