### ISSUE TITLE
Can we realign the identity/about section a bit?

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKnet-Website#104]
Especially this part:

![grafik](https://user-images.githubusercontent.com/8081055/157232433-d74bf4a7-b802-45e8-8ec3-1ac30b2df87a.png)

**Comment by MartinSchott** [comment]
Yes, that's how it looks now: (see below)
I committed this version to the `development` branch

**desktop**
(in desktop view it could be positioned even more to the outside, but I think it would look weird)
![grafik](https://user-images.githubusercontent.com/8080649/158878264-17c2a27f-cd84-46c2-887a-dfcd02db3109.png)

**mobile**
![grafik](https://user-images.githubusercontent.com/8080649/158878360-3b8101b4-e466-47e0-9701-4ff11abfa125.png)
