### ISSUE TITLE
Resources linking to Wikifab

### ISSUE THREAD

**Issue by yara89** [opencultureagency/ASKnet-Website#105]
The resources linking to Wikifab:

-  DIY solar panels
-  Repair cafe'
- Open Workshop Setup

are appearing without text (see Screenshot)

they should be linking to: https://wikifab.org/wiki/DIY_Solar_Charger instead of https://wikifab.org/wiki/DIY_Solar_Charger/

As it seems to be automatically adding a slash ( / ) to the end of the URL, it links to the wrong page.

<img width="1314" alt="URL with :" src="https://user-images.githubusercontent.com/60362934/159473935-d1ee72f8-12a8-4d6f-93e5-410bae5e154e.png">

**Comment by MartinSchott** [comment]
@yara89 thanks, well spotted! That's weird that wikifab does that. But anyways, I changed the links accordingly
