### ISSUE TITLE
Add Hub: CC4D

### ISSUE THREAD

**Issue by Math-TECH-Hub** [opencultureagency/ASKnet-Website#113]
### Name

Community Creativity For Development (CC4D)

### Subtitle

Community Creativity for Development (CC4D) is a Youth led community-based organization formed  in August 2019 formally and was founded by South Sudanese Refugees professionals (Youths) who  saw a gap in repair, reuse and maintenance of Electronics.  CC4D already has a presence on the ground, implementing digital literacy training programs and  mobile repairs and maintenance of electronics with its main aim “To digitally connect Communities  while protecting the environment from carbon emission and landfill using the available resources for  self-reliance and sustainable development.”

### Image

![wirc6](https://user-images.githubusercontent.com/57042950/162809924-5c08e583-0c5f-40ad-98c0-faac465371f7.jpg)

### Location

Eden II, Rhino Camp - Uganda

### Mission Statement

CC4D-Uganda strives to connect communities while protecting the environment from  global warming using the available resources for self-reliance and sustainable development

### Vision Statement

“A transformed and committed society fully in control of their social economic wellbeing using the  available resources to reduce poverty, building peaceful and prosperous communities”.

### Logo

![CC4D LOGO NEW](https://user-images.githubusercontent.com/57042950/162810245-eac4f7b3-9c33-47ba-bbd4-fa49e30e5ff2.png)

### Website

https://www.facebook.com/CC4D.Uganda/

### Description

CC4D-UGANDA aspires to implement sustainable community intervention initiatives targeted at 
positively transforming both the refugees and the communities that host them, with an emphasis on 
safe use of information and communication technology (ICT) while protecting the environment from 
global warming and improve the lives of both the refugees and host community in Uganda. Open access 
to information and Information broadcasting is an important aspect of our strategic plan to impact 
communities in which we operate. Improving the health and well-being of community residents is 
important to us, for example, through:
● Organizing repair café events
● Advocacy on repair and reuse
● Access to information and Hardware
● Providing digital literacy skills 
● Awareness raising on E-Waste management
● Collection and recycling of E-waste
● Promotion of peaceful coexistence 
![photo_2021-10-26_19-24-28](https://user-images.githubusercontent.com/57042950/162810425-4939e3ef-3983-4f1d-9867-2bfa3fcc0ff8.jpg)
![IMG_20211020_123735_066](https://user-images.githubusercontent.com/57042950/162811006-28ef8fda-f649-477a-8399-400dfd81f705.jpg)

**CORE VALUES**
1. Determination and commitment
2. Faithful
3. Inclusive community
4. Human dignity
5. Transparency and Accountability
6. Teamwork and Cohesive team building
7. Integrity
8. Creativity
9. Zero tolerance to corruption
10. Result oriented
11. Environmental justices and sustainable community development

**THEMATIC AREAS OF OPERATION**
1. Environmental protection
2. Youth empowerment on digital literacy and Livelihood Support
3. Peace Building

![IMG_20220404_152857_052](https://user-images.githubusercontent.com/57042950/162811304-026ffa6b-c7d6-4572-b66b-45a4b83e6d18.jpg)
![IMG_20220404_153019_831](https://user-images.githubusercontent.com/57042950/162811467-c4375f03-3392-4276-9736-707a3b277722.jpg)
![IMG_20211022_120738_97](https://user-images.githubusercontent.com/57042950/162812241-7d558a3b-287b-48d6-84d8-01109c0e161e.jpg)
![WRCC1](https://user-images.githubusercontent.com/57042950/162813345-4c640269-d44b-443a-b7a5-1df9c045c9c9.jpg)

### Social Media

https://www.facebook.com/CC4D.Uganda/

**Comment by MartinSchott** [comment]
@Math-TECH-Hub 
Hey Mathew, the logo looks a bit distorted and therefore not circular... is this an accident or is the logo meant to be this way? 
Also I'm not sure who approves the addition of a new hub...  Who knows more @Iamjaiksana @timmwille ?

**Comment by eMPee584** [comment]
.. here's a vectorized and re-rounded version of the logo.. it's not perfect because I checked a wrong option but I guess it's „good enough for now“ 😅

![community-creativity-4-development](https://user-images.githubusercontent.com/1227833/193671406-aa685bc5-4d88-48d9-af5f-90877fca66bf.png)
![community-creativity-4-development](https://user-images.githubusercontent.com/1227833/193671417-94bd178d-1f06-4595-940c-842b6f61ac53.svg)

oh and the SVG has a transparent background so that has to be taken into consideration when processing, or a white rectangle has to be put in the background

**Comment by dutkulang** [comment]
woooooow!!!!
