### ISSUE TITLE
fix "add tool" and "add resource" link 

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#149]
"add-xxx.yml" need to be "new-xxx.yml" to make the links work - they should go to the issue template

![grafik](https://user-images.githubusercontent.com/8080649/215711587-5f875a72-1596-401b-b71d-ecf226f85a55.png)

- the description of the issue template should refer to the title of the suitable wiki page

**Comment by timmwille** [comment]
best to change the code not the file name as it is already referenced in the wiki with this URL (e.g):

https://github.com/ASKnetCommunity/ASKnet.Community/issues/new?assignees=&labels=content-submit%2Cnew-resource&template=add-resource.yml&title=Add+Resource%3A+

**Comment by timmwille** [comment]
linked to #151
