### ISSUE TITLE
Adding content (Media Production on the website)

### ISSUE THREAD

**Issue by romeoplat** [opencultureagency/ASKnet-Website#172]
Hello @timmwille , Here is content for the tab, Media Production that should replace the media tab now existing on the website, ## ** Tab 8: Media Production
 
---

**Media Productions**

Welcome to the #ASknet network's Media Productions hub. Here, we proudly present a collection of impactful podcasts and media productions created by our member organizations. These productions showcase a diverse range of stories, experiences, and insights, all with the aim of informing, inspiring, and connecting communities.

Explore the captivating narratives, educational content, and thought-provoking discussions brought to you by our dedicated member organizations. Each production reflects their commitment to making a positive change in the world.

Let's dive into the world of storytelling and discovery through the following productions:

---

 
### Youth Empowerment Foundation

**Refugee Youth Podcast**
- Description: Welcome to the Refugee Youth Podcast, a platform dedicated to sharing the stories and experiences of refugees living in Uganda. This is a Youth Empowerment Podcast, produced and hosted by young refugees in the Pagirinya refugee settlement sharing their experiences and stories with the aim of educating, inform, and evoke positive change.
 
- Link: [Listen on SoundCloud](https://on.soundcloud.com/RMwXEqY6LbAseCBx8)

### CC4D

**E-waste Awareness Video**
- Description: This video is produced as a result of the E-waste management through training and awareness on repair, reuse, and upcycling projects in collaboration with _r0g agency and funding from BMZ. It is intended to create awareness about the International Repair Day and the value and importance of repair in Refugee.
- Link: [Watch on YouTube](https://www.youtube.com/watch?v=Zt4bFndoXM0)

### GoGirls ICT Initiative

**Amplified Gender Voices Podcast**
- Description: The "Amplified Gender Voices Podcast" by GoGirls ICT Initiative. Every woman's story is a powerful force for change. In this podcast, we bring you inspiring stories, thought-provoking interviews, and impactful conversations that shine a light on the remarkable women of South Sudan. At some point in this podcast, you will be informed, inspired, empowered, and moved by the Amplified Gender Voices Podcast.
 
- Link to the Podcast: [Listen on SoundCloud](https://soundcloud.com/agvpodcast)
- RSS Feed: [RSS Feed](https://feeds.soundcloud.com/users/soundcloud:users:1289645559/sounds.rss)

**Classroom on Phone Series**
- Description: #ClassroomOnPhone is a pre-recorded learning program where learners are taught science subjects with the aim of enhancing the love and practice of science in primary and secondary school students.
- RSS Feed: [RSS Feed](https://feeds.soundcloud.com/users/soundcloud:users:1289645559/sounds.rss)
- SoundCloud: [Listen on SoundCloud](https://soundcloud.com/classroom-on-phone)
- Spotify: [Listen on Spotify](https://gogirlsict.org/classroomonphone-series-gogirls-learning-podcast/)
- Feedback on Classroom on Phones series implementation in schools: [Watch on YouTube](https://www.youtube.com/@gogirlsictinitiative4202)

### #ASKnet

**ASKPodcast**
- Description: "ASKPodcast: where technology meets community, and innovation solves problems. Join us as we delve into the world of open technology and explore the impact it has on communities in South Sudan and Uganda. From local organizations to community leaders, and individuals, we bring you the stories of change-makers who are using technology to create a better future for their communities."
- Listen on: [Jiosaavn](https://www.jiosaavn.com/shows/ask-podcast/2/pV8HqsZcUAI_)
- Listen on: [Spotify](https://podcasters.spotify.com/pod/show/ask-podcast6)

**Stream Video Conversations**
- Link: [Watch on YouTube](https://www.youtube.com/@_ASKnet)

### Platform Africa

**Refutories**
- Description: "Refutories" is a word that emanates from Refugee stories, telling refugee stories, with interviews of different refugees on their experiences living in the refugee camp, like sex education, cultural aspects, etc. Listen to the different perspectives of the refugees; this is a brainchild of Platform Africa.
- Link: [Listen on SoundCloud](https://on.soundcloud.com/QAbKZCdG9wY34Nos6)

**Comment by timmwille** [comment]
thank you @romeoplat I will forward to @yara89 and @MartinSchott 

Clarification: is there a planned maintenance approach to keep the content up to date? I think this section will have a lot of incoming new sections right? Maybe we structure it in a way so it is listed as modules similar to the "Resources" on a separate page, or similar to the old "Hubs" popup approach? with a simple "add media product" button that points to an issue template form to be submitted? 

@MartinSchott if you have a good idea on how to maintain all these website modules efficiently or even reduce complexity (especially Resources will probably be soon a separate page that is linked to, it is hard to maintain and doubles with training.asknet.community modules and resources) please comment! :)

**Comment by timmwille** [comment]
> Clarification: is there a planned maintenance approach to keep the content up to date? I think this section will have a lot of incoming new sections right? Maybe we structure it in a way so it is listed as modules similar to the "Resources" on a separate page, or similar to the old "Hubs" popup approach? with a simple "add media product" button that points to an issue template form to be submitted?

what do you think/can say about that @romeoplat ?

**Comment by MartinSchott** [comment]
I created a new design and a technical structure behind it. New Podcasts and videos can be added in the file settings.yml . In the future we could think about another way of adding podcasts, videos etc. Also, given the new structure (the grid is based on "shuffle.js") it would be possible to have filtering functions similar to the ones on the LEAD front page.
