### ISSUE TITLE
Link social media icons

### ISSUE THREAD

**Issue by yara89** [opencultureagency/ASKnet-Website#19]
Social media icons should link to corresponding pages.

**Comment by yara89** [comment]
links on the page, especially for social media, should open in new tab, should I go ahead and do that to external links that don't, or would that be taken to beta?...
target="_blank" 
@MartinSchott @timmwille ?

**Comment by MartinSchott** [comment]
yeah you can go ahead - or is this already taken care of (issue is closed)?

**Comment by yara89** [comment]
yea it's done! and closed
