### ISSUE TITLE
Add section "Podcast #ASKradio" to website

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#2]

**Comment by timmwille** [comment]
This is the project that @romeoplat is coordinating, connected to this
https://anchor.fm/refutories/episodes/R-and-R-ASKvox-podcast-euegfr/a-a560p8s

**Comment by bmen** [comment]
For new sections new HTML templates must be created in "/_includes". It would be good if it could be described in more detail how such a podcast section should look like. It is also enough to say: "similar to section XY". Of course it would be better to create an example image ;) Then I can create them. This also applies to the issue #1

**Comment by timmwille** [comment]
I would not create a full section for now but just as one of many resource raster blocks/tiles in a sections

**Comment by timmwille** [comment]
should be a resource for now @MartinSchott  #50 #48 

# #ASKradio
### #ASKnet Storytelling Podcast

**Comment by romeoplat** [comment]
I am planning on doing a vast #ASKradio podcast and I think it would be nice to include that content as part of the website.

**Comment by MartinSchott** [comment]
I added it as a resource. Hope the following link is still the correct one: https://anchor.fm/refutories/episodes/R-and-R-ASKvox-podcast-euegfr/a-a560p8s 
It will be visible on the website as soon as the current release is finished (which will hopefully be the case on 14.12.2021).
