### ISSUE TITLE
Can we include other Repositories to appear on the Website?

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKnet-Website#20]
We need all Open Guides and other Repository Content some how visualized on the website, before pointing to the repository.

@bmen @yara89

**Comment by yara89** [comment]
@timmwille @bmen I am not sure honestly,

**Comment by bmen** [comment]
Yes, I have implemented a plugin to display Markdown files from other repositories: jekyll-remote-include

```
{% remote_include https://example.com/README.md %}
```
