### ISSUE TITLE
Hubs pages pictures loading and open external links in new tab

### ISSUE THREAD

**Issue by yara89** [opencultureagency/ASKnet-Website#21]
In hubs pages, only the top photos are showing on the site, the logo and second photo do not load on the site (on the github directory they do..) @timmwille 

Also, I would make sure the links to the external websites of each hub, actually open in new tab, rather than on the same window...

<img width="707" alt="platform" src="https://user-images.githubusercontent.com/60362934/139028528-ba08ac6f-f64c-4199-b533-c4d0c2bfa336.png">

**Comment by timmwille** [comment]
@yara89 might be fixed but please check the URLs might be related to #25 #45 and while going through hub pages check for missing links (social media etc.) in Issue #46
