### ISSUE TITLE
unify colors ("corporate identity") of #ASKnet website, LEAD, #ASKtraining page

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#26]
(not sure where this issue should be posted in)

Goal: communicate that the three pages are part of the same thing. 

So, are there official  #ASKnet colors? Should we use the r0g colors? @timmwille

**Comment by timmwille** [comment]
definitly not the r0g colors, it should be its own CI ... we can ask the members for input. Black and white and the colors from all open guides are the only ones in play currently

**Comment by timmwille** [comment]
we also could create a Corperative Design Repo reffering to the open guides
https://openculture.agency/open-educational-resources/

also a Designer would be available if we need one, she is also responsible for the not yet published `Open Collaboration Guide` 😉

**Comment by bmen** [comment]
I would say we make a repo called "CI - Colors, Fonts, Logo" and put in the colors and logos we already know and discuss if they are the right ones.

**Comment by timmwille** [comment]
I'm not sure if we are the ones defining the Identity: https://www.lucidpress.com/blog/10-best-branding-corporate-identity-design-examples

So rather call it simply "ASKnet Design - Colors, Fonts, Logo" or "Visual Identity" Repo but in general it is time to have it all in one, I like it!

**Comment by MartinSchott** [comment]
we could use the colors of the open documentation guide, as @timmwille suggested

https://github.com/opencultureagency/Open-Documentation-Guide

**Comment by timmwille** [comment]
@bmen you have an example for @MartinSchott ?

**Comment by MartinSchott** [comment]
the new repository is here: https://github.com/ASKnetCommunity/ASKnet-Design

can you check it @timmwille @bmen ?

I chose the MIT license, I hope that is correct.

Fonts: I just kept the Source Sans Pro font for texts (as a link), as I didn't find the other ones very fitting. [Bearbone Stamp](https://www.dfonts.org/fonts/bearbone-sans/) could also be nice for very big headlines, but I found a cost-free link and a costly (1,50$) link so I'm not sure if we can use it → I didn't include it.

**Comment by timmwille** [comment]
I think as the posters are under CC-BY-SA License at least CC-BY (as it is less complicated to reference/apply to) is suited, but similar if not compatible to MIT so should be fine for now.

Also all 3 Platforms look similar, some smaler detailes could be chaged soon → other fonts should be named as reference in their context (Open Documentation Guide) but for the Websites we ONLY use Open Source fonts (indicators: have an Open License, free of charge)

So from my side this issue can be closed and another issue for finetuning can be opened in the new Repo
https://github.com/ASKnetCommunity/ASKnet-Design
