### ISSUE TITLE
Content-Proposals: top ASKnet description text

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#30]
Proposals for the following website section please in the comments.

![image](https://user-images.githubusercontent.com/8080649/140398630-38de1171-22d4-4433-90e7-883e21aa8af8.png)

**Comment by chardso** [comment]
[Uploading Documentation for the Second Remote Repair Cafe _ Eden.pdf…]()

**Comment by chardso** [comment]
![Uploading IMG_20211220_215122_835.jpg…]()

**Comment by timmwille** [comment]
@Iamjaiksana feel free to add you thoughts here :)

**Comment by MartinSchott** [comment]
closed for now
