### ISSUE TITLE
Add Link to create new timeline event

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#38]
I created the issue form for proposing a new event in the timeline. But I'm not able to create a nice area/button in the timeline. 

The link should open in a new window, I think, and is the following: 

https://github.com/ASKnetCommunity/ASKnet.Community/issues/new?assignees=&labels=content-submit%2Cnew-timeline-event&template=new-timeline-event.yml&title=Add+Timeline+Event%3A+

this circle should be the link: 
![grafik](https://user-images.githubusercontent.com/8080649/145090265-900fcd14-7309-4ccf-95e8-822b6d2727a4.png)

**Comment by timmwille** [comment]
We might want to link the timeline in the Menu as well? → we rather might want to call it "History"?

**Comment by timmwille** [comment]
Do you mean to use the template issue directly or prepare an issue for the whole section?

**Comment by timmwille** [comment]
> Do you mean to use the template issue directly or prepare an issue for the whole section?

ah I checked the URL so @bmen please reference here: 
![image](https://user-images.githubusercontent.com/8081055/145089697-436b3d1c-2239-4a50-91d6-ecc4e5c2f767.png)

**Comment by MartinSchott** [comment]
I would use the issue template directly, meaning new issues are created for new timeline events, as its not possible (afaik) to make an issue form that just adds comments to an existing issue (would be called an "issue comment form"...). The issue form includes a tag exclusively for timeline events.
