### ISSUE TITLE
Corrections for navigation

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKnet-Website#42]
- [x] #ASKnet - stays, just jump-mark needs to be changed - #41
- [x] LEAD -> Experts
- [x] delete #ASKotec
- [x] delete #ASKtraining
- [x] keep #ASKtools
- [x] add "Resources"
- [x] add "Timeline"
- [ ] Github just as Icon

(so, new menu has: #ASKnet, Hubs, Experts, #ASKtools, Resources, Timeline, Contact, Github-icon)

**Comment by MartinSchott** [comment]
I left github as text because there is enough space and creating an icon would have taken a lot of time
