### ISSUE TITLE
check and add all relevant URLs and social media links in the hub pages

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#46]

**Comment by yara89** [comment]
I noticed that YEF have a new Youtube channel, I could add it also.. (should I just go ahead and do such things?) or better to avoid any conflict..?

**Comment by MartinSchott** [comment]
you can go ahead and do it

**Comment by yara89** [comment]
@MartinSchott I already did :) last night, I also made the icons linking to social media open in a new tab,

I think the social media icons in the footer should do the same.. But those it seems should be in their _sass folder for the footer?  Do you know?

**Comment by MartinSchott** [comment]
@yara89 well spotted! Yeah, they should also have target="_blank". They were in the footer.html, I changed it
