### ISSUE TITLE
All sections for Alpha version

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKnet-Website#48]
### Menu - https://github.com/ASKnetCommunity/ASKnet.Community/issues/42
- [x] done

Logo - https://github.com/ASKnetCommunity/ASKnet.Community/issues/43
- [x] done

[sections here remain unchanged]

### LEAD
- [x] add Button "go to LEAD" (opens in new window, linking to https://lead.asknet.community/ )

### remove #ASKotec section
- [x] done

### remove #ASKtraining section
- [x] done

### #ASKtools
- has tiles like "Hubs" section
- tiles: ( **title** - subtitle - link)
  - **Loomio** - decision making - https://form.asknet.community 
  - **LEAD** - Local Experts - https://lead.asknet.community/
  - **Meet** - Online Sessions - https://meet.asknet.community/
  - **HedgeDoc** - Collaborative Documents - https://doc.asknet.community/
  - **Forms** - Create Surveys - https://form.asknet.community 
  - **#ASKotec** - Open Tech Training Kit - https://askotec.asknet.community 
  - **Training** - Open Training Configurator - https://training.asknet.community
  - **Sandbox** - GitHub Collaboration - https://github.com/ASKnet-Open-Training 
  - **Add Tools** - Add a tool - https://github.com/ASKnetCommunity/ASKnet.Community/issues/48
  - [x] all done
- find pictures for the tiles #51
  - [x] done

### remove Projects and Trainings section
- [x] done

### remove #ASKnet Team section
- [x] done

### remove About Us section
- [x] done

### new section "Resources"
- called "Resources" → Open Educational Training Resources
- has tiles like "Hubs" section
- tiles: ( **title** - subtitle - link)
  - **DIY Solar Charger** - Build a simple Solar Charger - https://wikifab.org/wiki/DIY_Solar_Charger
  - **#ASKotec** - Open Tech Training Kit - https://askotec.asknet.community 
  - **Open Workshop Setup** - Create a simple workspace setup - https://wikifab.org/wiki/DIY_Solar_Charger
  - **Repair Café** - Host a Repair Event - https://wikifab.org/wiki/Repair_Cafe%27
  - **GitHub Guidance** - Learn to collaborate using Github - https://asknet-open-training.github.io/Github-Guidance/
  - **Open Documentation Guide** - Share your Knowledge openly - https://github.com/opencultureagency/Open-Documentation-Guide
  - **#ASKradio** - Storytelling Podcasts from #ASKnet members - https://anchor.fm/refutories/episodes/R-and-R-ASKvox-podcast-euegfr/a-a560p8s
  - **Add Resources** - Add a resource - https://github.com/ASKnetCommunity/ASKnet.Community/issues/new?assignees=&labels=content-submit%2Cnew-resource&template=add-resource.yml&title=Add+Resource%3A+
  - [x] all done
- find pictures for the tiles #51
  - [x] done

### Logos 
- replace with Funder logos (r0g, BMZ)
- ![r0g_logo](https://user-images.githubusercontent.com/8080649/145101722-fec97389-6507-454a-87d2-386e709ae4a7.png)
- ![founder_BMZ](https://user-images.githubusercontent.com/8080649/145101727-560be7c3-d53f-44ca-ab18-e9f0e6528b96.jpg)
- [x] done

### contact
- remove subtitle
  - [x] done
- where does the email go? tbd → #52

### footer
- new link for social media icons: 
  - twitter: https://twitter.com/search?q=%23%23ASKnet&f=live
  - facebook: https://www.facebook.com/hashtag/asknet
  - linkedin: https://www.linkedin.com/search/results/content/?keywords=%23asknet&origin=SWITCH_SEARCH_VERTICAL&sid=GQE
  - github: https://github.com/ASKnetCommunity
  - instagram: https://www.instagram.com/explore/tags/asknet/
- [x] done

**Comment by MartinSchott** [comment]
(removed)

**Comment by timmwille** [comment]
🔸🔹▪️https://asknet.community Website/Portal/(Blog?) (GitHub page)
🔸🔹▪️https://lead.asknet.community Directory (GitHub page)
🔸▪️https://meet.asknet.community forwards to https://meet.openculture.agency/r/ASKnet 
🔸▪️https://doc.asknet.community to HedgeDoc
🔸▪️https://form.asknet.community to OhMyForm
🔸▪️https://loomio.asknet.community to Loomio
🔸▪️https://askotec.asknet.community forwards to askotec.openculture.agency
🔸🔹▪️(later) training.asknet.community #ASKtraining (GitHub page)

**Comment by timmwille** [comment]
https://github.com/ASKnet-Open-Training → Sandbox GitHub

**Comment by timmwille** [comment]
Public Telegram Group? → tricky due to spam but would be nice to add @CommunityRepair to our Repair Community

**Comment by timmwille** [comment]
Resource → https://wikifab.org/wiki/Open_Workshop_Setup

**Comment by timmwille** [comment]
Resource → https://wikifab.org/wiki/DIY_Solar_Charger

**Comment by timmwille** [comment]
Resource → ASKotec
Resource → https://wikifab.org/wiki/Repair_Cafe%27
Resource → https://asknet-open-training.github.io/Github-Guidance/
Resource → https://github.com/opencultureagency/Open-Documentation-Guide

**Comment by MartinSchott** [comment]
@timmwille regarding the logos: is it okay if the BMZ logo links to https://www.bmz.de/en ?

**Comment by timmwille** [comment]
> @timmwille regarding the logos: is it okay if the BMZ logo links to https://www.bmz.de/en ?

I think even without Logo is good, even better maybe
