### ISSUE TITLE
Content-Proposal: section "Resources" 

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#56]
Proposals for the following website section please in the comments. Just proposals for the description text (see image). For proposals for new **Resources** to be presented, please use [this link](https://github.com/ASKnetCommunity/ASKnet.Community/issues/new?assignees=&labels=content-submit%2Cnew-resource&template=add-resource.yml&title=Add+Resource%3A+).

![grafik](https://user-images.githubusercontent.com/8080649/145848578-42838d22-3cef-4470-8b40-4072396bd498.png)

**Comment by chardso** [comment]
![IMG_20211218_204003_414](https://user-images.githubusercontent.com/71114711/146812616-c3d90e24-0fb5-4340-a527-8f24f67d9078.jpg)

**Comment by timmwille** [comment]
@chardso as training resources in digital form more is needed then a picture but in this case we're looking for a small description

**Comment by MartinSchott** [comment]
closed for now
