### ISSUE TITLE
Change license to CC-BY-SA 4.0

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKnet-Website#6]

**Comment by timmwille** [comment]
We might want to keep the MIT for the code but want to change the content to CC-BY-SA? 
or we keep it simple to just MIT?

**Comment by timmwille** [comment]
I think we don't need Copyleft in this case, as copying will be ok and not further restrictions needed. 
But for Alpha we can also just leave it the way as it is → focus on giving external sources credits and mentioning the CC-BY-SA for content in the footer.

**Comment by timmwille** [comment]
I've created another linked issue #64 but this one can be closed
