### ISSUE TITLE
#ASKtools description

### ISSUE THREAD

**Issue by yara89** [opencultureagency/ASKnet-Website#61]
Make the tools and their descriptions more clear for users. 

precise title and subtitle
- up to two lines... 

---
- [x] LEAD - Local Experts - https://lead.asknet.community/
- [x] Online Meetings - Online Sessions - https://meet.asknet.community/
- [x] Text Editor - Collaborative Markdown Documents - https://doc.asknet.community/
- [x] #ASKotec Toolbox - Open Tech Training Kit - https://askotec.asknet.community
- [x] GitHub Sandbox - GitHub Collaboration - https://github.com/ASKnet-Open-Training
- [x] Survey Forms - Create Community Surveys - https://form.asknet.community
- [x] Training Configurator - Open Training Configurator - https://training.asknet.community
- [x] Loomio - Proposals & Decision Making - https://form.asknet.community
- [x] Add Tools - ...

**Comment by MartinSchott** [comment]
the headings and subheadings can be changed in the folder `tools` . Each tool has a separate file, and the subheading is the value after `subtitle: ` (so pretty straight-forward, but a lot of files to edit...)

**Comment by timmwille** [comment]
@MartinSchott I changed the order and some wording but I think it could be improved - if you find a good understandable Title and Short-description for each @yara89 would be great → thx

**Comment by MartinSchott** [comment]
I changed the order accordingly

**Comment by yara89** [comment]
Added the short descriptions...

**Comment by timmwille** [comment]
Ok I think we still need to even out things → should be on point and same height if possible, not lots of pictures are cut of and the text is a bit much too read/to many words (I made the development branch the render branch, so check out directly)

**Comment by yara89** [comment]
for the #ASKtools, the descriptions were added in the .md files, but the images I think by Martin, wasn't sure if I should go ahead and resize and crop etc... to avoid any conflicts,

I think that there should be a way, to make the containers (both the images and text) a fixed size, and that way you avoid any issues.. I could also, resize the images, so they look neater but was not sure I should go ahead and do  something like that, or to communicate it (incase someone else is working on it) should we just communicate these details  and decide who/when each one does something? 
@MartinSchott, maybe we could have another call some time, and split more tasks amongst us?

**Comment by MartinSchott** [comment]
@yara89 yeah I found a CSS setting that makes all pictures the same height. So no resizing or cropping of the pictures is needed. 
I guess in terms of working together, it's good to communicate first, to check if the other one is already on it. I try as much as possible to always focus on 1 project, I find it easier. I think at the moment there are no issues on the #ASKnet website that dont requite timm or basti to give more input...
