### ISSUE TITLE
domain redirection doesn't work

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#72]
settings > pages
![grafik](https://user-images.githubusercontent.com/8080649/147786063-2d1523e0-d8ae-402a-8173-a25441adadd7.png)

When I change something in the repo, the changes don't show when I access the website under www.asknet.community (locally it works)

**Comment by timmwille** [comment]
this is unrelated to #73 right? 

Please check this @bmen as it still seems to be an issue:

![image](https://user-images.githubusercontent.com/8081055/150025547-bb515493-0efe-473b-9901-fa944261047b.png)

**Comment by MartinSchott** [comment]
The problem that changes weren't visible on the website was something else and it's fixed. I assumed wrongly that it was connected to that domain problem → I'll change the title.

**Comment by bmen** [comment]
Duplicated: #44
