### ISSUE TITLE
have sub-pages for hubs, resources, tools

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#75]
- option to link to sub-page OR just have an external link
- on the sub-page of resources / tools may be an include of a .md file of another repo

**Comment by MartinSchott** [comment]
here the info on how to include data of other repositories: https://github.com/ASKnetCommunity/ASKnet.Community/issues/20

**Comment by timmwille** [comment]
#112 is connected here?

**Comment by timmwille** [comment]
done from what I understood

**Comment by timmwille** [comment]
(only Hubs are subpages for now, can change in the  future)
