### ISSUE TITLE
include official #ASKnet identity in the website

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#77]

**Comment by MartinSchott** [comment]
first draft: 

![grafik](https://user-images.githubusercontent.com/8080649/148134981-9305215b-de0e-4323-9a88-d722a4030738.png)

please feedback @ everyone who has an opinion & @timmwille

**Comment by MartinSchott** [comment]
second draft (per Timms Idea): 

![grafik](https://user-images.githubusercontent.com/8080649/148415595-51cda5cd-c9bb-40a9-9fdf-ae0fddebc82a.png)

**Comment by timmwille** [comment]
I like the second one more due to its easier to grasp form → though might be different on screen/phone → does all fit into the section on the screen when one clicks on "About" @MartinSchott ?

what do you think @ASKnetCommunity/coordinators ?

**Comment by MartinSchott** [comment]
> I like the second one more due to its easier to grasp form → though might be different on screen/phone → does all fit into the section on the screen when one clicks on "About" @MartinSchott ?

Yes, it fits onto a phone screen - it took quite a while to figure out how to make it desktop and mobile friendly...

![grafik](https://user-images.githubusercontent.com/8080649/150191767-eb40329c-4f96-4fee-bd4f-87bb15350596.png)

**Comment by MartinSchott** [comment]
btw, this version is online now, I hope that's okay.

**Comment by timmwille** [comment]
some feedback from @Iamjaiksana here #104

**Comment by MartinSchott** [comment]
after talking to @timmwille I changed it again slightly, now all the five "2-line-blocks" are a bit further apart when the website is shown on a broad screen. (smartphone view is not changed)
Hope that's alright now.

![grafik](https://user-images.githubusercontent.com/8080649/164516025-bc879980-f215-483a-be8e-507d6cb8e60a.png)
