### ISSUE TITLE
Create Legal Notes / Credit file with reference to theme creator and other technologies

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKnet-Website#8]
Theme Creator: https://jekyll-themes.com/agency-jekyll-theme/

Technologies:
- https://getbootstrap.com/
- https://fontawesome.com/

Example: https://2032er.bmen.cc/CONTRIBUTER/

---
Can also go to Readme in a section

- [x] copyright name/creator/source/reference 
- [x] License note
- [x] URL to source

**Comment by timmwille** [comment]
is there anything else that was used from external sources?

**Comment by timmwille** [comment]
can go worst case into Beta Release @MartinSchott

**Comment by timmwille** [comment]
@bmen is this still the same? or do we need to add other credits for fonts etc. or other used resources?

**Comment by timmwille** [comment]
I think we postpone this to Beta

**Comment by MartinSchott** [comment]
can be written into the readme.md file, doesn't need to be on the website itself (as long as repo is linked from website)

**Comment by MartinSchott** [comment]
added to readme:
![grafik](https://user-images.githubusercontent.com/8080649/148419608-f80bdfca-fbdf-4c10-81c2-e7c8609e9ed2.png)

please give okay/not-okay @timmwille as I'm still not so fluent in copyright topics

**Comment by timmwille** [comment]
looks great if all are included → so for now lets close it :)
