### ISSUE TITLE
fix contact form

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKnet-Website#87]
- [ ] also mark .agency etc. endings as valid emails
- [ ] phone number is mandatory although it should not be (also not marked as such)

**Comment by bmen** [comment]
The technology behind the contact form is from https://formspree.io/ and we have no influence on the technical implementation. If no *.agency email addresses can be used, then another technology from another provider must be found for this. An alternative would still be to enter the email address directly on the website, so that the user can contact via the email address itself.

**Comment by timmwille** [comment]
Ok so here the Form Phone section could be removed or made optional:

https://github.com/ASKnetCommunity/ASKnet.Community/blob/main/_data/sitetext.yml

(btw. the spanish version can be deleted as well)


might also require editing here:

https://github.com/ASKnetCommunity/ASKnet.Community/blob/main/_includes/contact.html


here is the main file to be edited it seems:

https://github.com/ASKnetCommunity/ASKnet.Community/blob/main/assets/js/contact_me.js


---


This is also good to prevent spam:

https://help.formspree.io/hc/en-us/articles/360013580813-Honeypot-spam-filtering

**Comment by timmwille** [comment]
more hints:
- for the phone it just needs to be disabled the "required" or removed fully 
- for the email verification the problem seems to be here with regex in line `965`:
https://github.com/ASKnetCommunity/ASKnet.Community/blob/main/assets/js/jqBootstrapValidation.js

`regex: "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}",`

as far as I understand the `{2,4}`is limiting the input after the domain dot `.` to max. 4 charaters !!?

**Comment by hoijui** [comment]
yes, after the last `.`, so `...@google.com` is fine, `...@fabcity.hamburg` is not.
Good find! :-)

**Comment by hoijui** [comment]
I am totally not into this issue/problem, but this smells like a possible violation of [fail fast](https://en.wikipedia.org/wiki/Fail-fast).
What happens if this regex does not fit?
(btw, you can link directly to the line in the file by clicking on the line number:
https://github.com/ASKnetCommunity/ASKnet.Community/blob/main/assets/js/jqBootstrapValidation.js#L965 )

**Comment by timmwille** [comment]
@hoijui do you have a good suggestion for an email regex? one that characterizes E-Mail but does not limit the domain ending so much?
The error Message currently is a bit weak :)

**Comment by hoijui** [comment]
You could just remove the `4`, to make it `{2,}`, which means at least 2 (without upper bound).

**Comment by timmwille** [comment]
> You could just remove the `4`, to make it `{2,}`, which means at least 2 (without upper bound).

ok sounds good I found this page but honestly I'm not skilled enough in regex to find the fitting option:
https://emailregex.com

edit: the Swift option seems to be the closest/best `[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}`

**Comment by hoijui** [comment]
As I see it, this regex'es main task is, to make sure the user does not enter something other then his email (as in, mixes up fields).
with a regex alone, it is impossible to check if an email is valid. for that one would have to send an email and check the response from the server. So in my yes, as long as there is an `@` somewhere in the field, and something before and after it, it is good enough.
For example, I do not know if there are first level domains (com, org, hamburg, ...) that contain a number, or if there will be any in the future. If so, then this regex would again fail.
So the simplest thing, that should not ever fail, would be `.+@.+` (kinda looks like a crying clown-face, no? :D ).

**Comment by timmwille** [comment]
@bmen is this done?
