### ISSUE TITLE
Create wiki start-page

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#96]

**Comment by timmwille** [comment]
![grafik](https://user-images.githubusercontent.com/8081055/157764200-3c49dca4-224b-4c22-9612-79995e9912a3.png)

**Comment by timmwille** [comment]
![grafik](https://user-images.githubusercontent.com/8081055/157765412-1ba0b347-9195-4e75-ae6e-1d7f3244c704.png)

**Comment by timmwille** [comment]
# #ASKnet Website 
## How to navigate
1. `About` #ASKnet - Who we are, what values an mission we commit to
2. `Hubs` - The organisations who stand behind the "Access to Skills and Knowledge network" - [**add one**](#)
3. `Experts` - [L.E.A.D](https://lead.asknet.community) the Local Expert Action Directory are the people who shape #ASKnet - [**find and add your expertise**](#)
4. `Resources` - Open Educational Training Resources to be used for [#ASKtraining](https://training.asknet.community) - [**Add a Resource**](#)
5. `#ASKtools` - The platforms and tools we use - [**Suggest a new tool**](#)
6. `Timeline` - The History Milestones of [#ASKnet](https://asknet.community)
7. `Contact` - connect with us

## Contribute
### Tutorials for our Peers
- HowTo - add Hub - Expert - Resource - Tool - Milestone

### Technical Documentation
- Specs
- [Workflows](#) (Git Setup, Pull Requests, Merge Cycle, Local Setup, Content Review, Release)
- HowTo - add/update Content - add Images - prepare Website Review
- References

**Comment by bmen** [comment]
See comments in https://github.com/ASKnetCommunity/LEAD/issues/218

**Comment by timmwille** [comment]
fixed https://github.com/ASKnetCommunity/ASKnet.Community/wiki/asknet-community/ 

For Technical documentation all Wikis/Platfoms need a section (Specs, References, HowTos for Maintainers that are not specific to a section etc.)
